[package]
name = "input"
version = "0.1.0"
authors = ["Jan Trefil <8711792+htrefil@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2.22", features = ["full"] }
mio = { version = "0.6.22" }
libc = "0.2.77"

[build-dependencies]
bindgen = "0.55.1"